[build.environment]
  NODE_VERSION = "18"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/starter/*"
  to = "/starter/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://kolibry.dev/"
  status = 301
  force = true
