name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/
      - run: npm i -g @nyxb/nyxi
      - run: nyxci
      - run: nyxr ci:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
      - run: npx github-craftchangelogs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
